use BD_SUPERMERCADO

-----------------------PUNTO 1
DECLARE @FECHA DATE = '2013-12-31'
SELECT TOP 1 NOMBRE_SUPERMERCADO, CANTIDAD,  DESCRIPCION_TIPO, FECHA_VENTE  FROM TIPO_PRODUCTO AS TP
INNER JOIN FACTURA AS FC  
ON TP.ID_TIPO_PRODUCTO = FC.ID_PRODUCTO
INNER JOIN VENDEDOR AS VD
ON FC.ID_VENDEDOR = VD.ID_VENDEDOR
INNER JOIN SUPERMERCADO AS SM
ON SM.ID_SUPERMERCADO = VD.ID_SUPERMERCADO
INNER JOIN CIUDAD_SUPERMERCADO AS CSM
ON CSM.ID_CIUDAD_SUPERMERCADO = VD.ID_SUPERMERCADO
WHERE DESCRIPCION_TIPO = 'Carnicos' AND FECHA_VENTE <= @FECHA
ORDER BY CANTIDAD DESC
GO


-----------------------PUNTO 3

SELECT NOMBRE_VENDEDOR, NOMBRE_SUPERMERCADO, sum(VALOR_VENTA) AS TOTAL 
FROM FACTURA AS FC
INNER JOIN VENDEDOR AS VD
ON FC.ID_VENDEDOR=VD.ID_VENDEDOR
INNER JOIN SUPERMERCADO AS SM
ON SM.ID_SUPERMERCADO = VD.ID_SUPERMERCADO
GROUP BY NOMBRE_VENDEDOR, NOMBRE_SUPERMERCADO
ORDER BY TOTAL DESC
GO
-----------------------PUNTO 4


SELECT NUMERO_FACTURA, VALOR_VENTA, CONCAT(NOMBRE_VENDEDOR,' ',APELIDO_VENDEDOR)NOM_VENDEDOR
FROM FACTURA AS FC
INNER JOIN VENDEDOR AS VD
ON FC.ID_VENDEDOR=VD.ID_VENDEDOR
WHERE VALOR_VENTA >100000 AND VD.ID_VENDEDOR = 3
GO




